<?php

/**
 * @file
 * Thunder riddle install hooks.
 */

/**
 * Implements hook_menu_local_actions_alter().
 */
function thunder_riddle_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\views\Entity\View $view */
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('editor_media_search');
  if ($view && $view->status()) {
    $local_actions['riddle_marketplace.import']['appears_on'][] = 'view.editor_media_search.page';
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function thunder_riddle_preprocess_views_view(&$variables) {

  if ($variables['view']->id() == 'riddle_browser') {
    $variables['view_array']['#attached']['library'][] = 'thunder_riddle/entity_browser_view';
  }
}
